import { contextBridge, ipcRenderer } from 'electron'
import { BRIDGE_VERSION, type DevBoxApi } from '../shared/contracts'

const api: DevBoxApi = {
  version: BRIDGE_VERSION,
  workspaces: { list: () => ipcRenderer.invoke('workspaces:list'), create: (input) => ipcRenderer.invoke('workspaces:create', input), rename: (id, input) => ipcRenderer.invoke('workspaces:rename', id, input), remove: (id, input) => ipcRenderer.invoke('workspaces:remove', id, input), archive: (id) => ipcRenderer.invoke('workspaces:archive', id), current: () => ipcRenderer.invoke('workspaces:current'), select: (id) => ipcRenderer.invoke('workspaces:select', id) },
  dashboard: { get: (workspaceId) => ipcRenderer.invoke('dashboard:get', workspaceId) },
  github: { connectPersonalAccessToken: (token, name) => ipcRenderer.invoke('github:connectPersonalAccessToken', token, name), global: () => ipcRenderer.invoke('github:global'), list: () => ipcRenderer.invoke('github:list'), repositoryOwners: () => ipcRenderer.invoke('github:repositoryOwners'), repositoriesForOwner: (owner) => ipcRenderer.invoke('github:repositoriesForOwner', owner), assignedRepositories: (workspaceId) => ipcRenderer.invoke('github:assignedRepositories', workspaceId), setAssignedRepositories: (workspaceId, repositories) => ipcRenderer.invoke('github:setAssignedRepositories', workspaceId, repositories), refreshGlobal: () => ipcRenderer.invoke('github:refreshGlobal'), refreshWorkspace: (workspaceId) => ipcRenderer.invoke('github:refreshWorkspace', workspaceId), disconnect: (id) => ipcRenderer.invoke('github:disconnect', id), workItems: (workspaceId) => ipcRenderer.invoke('github:workItems', workspaceId) },
  jira: { connect: (input) => ipcRenderer.invoke('jira:connect', input), global: () => ipcRenderer.invoke('jira:global'), list: () => ipcRenderer.invoke('jira:list'), projects: () => ipcRenderer.invoke('jira:projects'), get: (workspaceId) => ipcRenderer.invoke('jira:get', workspaceId), setProject: (workspaceId, project) => ipcRenderer.invoke('jira:setProject', workspaceId, project), refresh: (workspaceId) => ipcRenderer.invoke('jira:refresh', workspaceId), disconnect: (id) => ipcRenderer.invoke('jira:disconnect', id), workItems: (workspaceId) => ipcRenderer.invoke('jira:workItems', workspaceId) },
  backups: { status: () => ipcRenderer.invoke('backups:status'), repositories: () => ipcRenderer.invoke('backups:repositories'), connectToken: (token) => ipcRenderer.invoke('backups:connectToken', token), configure: (repositoryId, acknowledgement) => ipcRenderer.invoke('backups:configure', repositoryId, acknowledgement), run: () => ipcRenderer.invoke('backups:run'), restoreLatest: (confirmation) => ipcRenderer.invoke('backups:restoreLatest', confirmation) },
  preferences: { getTheme: (workspaceId) => ipcRenderer.invoke('preferences:getTheme', workspaceId), setTheme: (workspaceId, theme) => ipcRenderer.invoke('preferences:setTheme', workspaceId, theme) },
  links: { openExternal: (url) => ipcRenderer.invoke('links:openExternal', url) },
  events: { subscribeWorkspaceChanges: (listener) => { const handler = () => listener(); ipcRenderer.on('workspace-data-changed', handler); return () => { ipcRenderer.removeListener('workspace-data-changed', handler) } } }
}
contextBridge.exposeInMainWorld('devbox', api)
