import { DevBoxStore } from './storage'
import { TokenVault } from './security'
import type { BackupRepository, BackupStatus, GitHubRepositoryOwner, WorkItem } from '../shared/contracts'
const API = 'https://api.github.com'
const BACKUP_PATH = 'devbox-backup/v1/latest.json'
class GitHubApiError extends Error { constructor(readonly status: number) { super(`GitHub API ${status}`) } }
export class GitHubService {
  constructor(private store: DevBoxStore, private vault = new TokenVault()) {}
  async connectPersonalAccessToken(token: string): Promise<void> { const value=token.trim(); if (!value) throw new Error('Enter a GitHub personal access token.'); const user=await this.request<{login:string}>('/user',value); const id=this.store.createGlobalGitHub(user.login,this.vault.encrypt(value),[]); this.store.markGlobalSynced(id) }
  async refreshGlobal(): Promise<void> { const integration=this.store.globalGitHub(); if (!integration) throw new Error('GitHub is not connected.'); try { const token=this.vault.decrypt(this.store.globalToken(integration.id)); await this.request('/user',token); this.store.markGlobalSynced(integration.id) } catch(error) { const message=error instanceof Error?error.message:'GitHub sync failed.'; this.store.globalIntegrationError(integration.id,message.includes('401')?'needs_reauth':'error',message); throw error } }
  async repositoryOwners(): Promise<GitHubRepositoryOwner[]> { const integration=this.store.globalGitHub(); if(!integration) throw new Error('GitHub is not connected.'); const token=this.vault.decrypt(this.store.globalToken(integration.id)); try { const [user, organizations]=await Promise.all([this.request<{login:string}>('/user',token),this.request<Array<{login:string}>>('/user/orgs?per_page=100',token)]); const owners=[{login:user.login,kind:'user' as const},...organizations.map((organization)=>({login:organization.login,kind:'organization' as const}))]; return Promise.all(owners.map(async(owner)=>({...owner,count:await this.repositoryCount(owner,token)}))) } catch(error) { const message=error instanceof Error?error.message:'GitHub owner lookup failed.'; this.store.globalIntegrationError(integration.id,message.includes('401')?'needs_reauth':'error',message); throw error } }
  async repositoriesForOwner(owner:string): Promise<string[]> { const integration=this.store.globalGitHub(); if(!integration) throw new Error('GitHub is not connected.'); const token=this.vault.decrypt(this.store.globalToken(integration.id)); const user=await this.request<{login:string}>('/user',token); const path=owner===user.login ? '/user/repos?per_page=100&affiliation=owner&sort=updated&direction=desc' : `/orgs/${encodeURIComponent(owner)}/repos?per_page=100&type=all&sort=updated&direction=desc`; const repositories=await this.listRepositoryNames(path,token); this.store.addGlobalGitHubRepositories(integration.id,repositories); return repositories }
  async backupRepositories(): Promise<BackupRepository[]> { return this.listBackupRepositories(this.token()) }
  async connectBackupToken(token: string): Promise<BackupRepository[]> { const value=token.trim(); if(!value) throw new Error('Enter a GitHub personal access token.'); const repositories=await this.listBackupRepositories(value); if(!repositories.length) throw new Error('This token cannot write to any private GitHub repositories.'); this.store.setBackupToken(this.vault.encrypt(value)); return repositories }
  async configureBackup(repositoryId: number): Promise<BackupStatus> { const repository=(await this.backupRepositories()).find((item)=>item.id===repositoryId); if(!repository) throw new Error('Choose a private repository you can push to.'); return this.store.configureBackup(repository) }
  async backupNow(): Promise<BackupStatus> { const status=this.store.backupStatus(); if(!status.repository) throw new Error('Choose a private backup repository first.'); try { const token=this.token(); const content=Buffer.from(JSON.stringify(this.store.backupSnapshot(),null,2)).toString('base64'); let sha: string|undefined; try { const existing=await this.request<{sha:string}>(`/repos/${status.repository.fullName}/contents/${BACKUP_PATH}?ref=${encodeURIComponent(status.repository.defaultBranch)}`,token); sha=existing.sha } catch(error) { if(!(error instanceof GitHubApiError && error.status===404)) throw error } const result=await this.request<{commit:{html_url:string}}>(`/repos/${status.repository.fullName}/contents/${BACKUP_PATH}`,token,{method:'PUT',body:JSON.stringify({message:'DevBox backup',content,branch:status.repository.defaultBranch,...(sha?{sha}:{})})}); this.store.markBackupSuccess(result.commit.html_url); return this.store.backupStatus() } catch(error) { const message=this.backupError(error); this.store.markBackupFailure(message); throw new Error(message) } }
  async restoreLatest(): Promise<void> { const status=this.store.backupStatus(); if(!status.repository) throw new Error('Choose a private backup repository first.'); try { const content=await this.request<{content:string;encoding:string}>(`/repos/${status.repository.fullName}/contents/${BACKUP_PATH}?ref=${encodeURIComponent(status.repository.defaultBranch)}`,this.token()); if(content.encoding!=='base64') throw new Error('Backup content encoding is not supported.'); this.store.restoreBackup(JSON.parse(Buffer.from(content.content.replace(/\n/g,''),'base64').toString('utf8'))) } catch(error) { throw new Error(this.backupError(error)) } }
  async refreshWorkspace(workspaceId: string): Promise<void> { const integration=this.store.globalGitHub(); if(!integration) throw new Error('GitHub is not connected.'); const repositories=this.store.assignedRepositories(workspaceId); if(!repositories.length) { this.store.replaceWorkspaceGitHubWork(workspaceId,[]); return } try { const token=this.vault.decrypt(this.store.globalToken(integration.id)); const user=await this.request<{login:string}>('/user',token); const items: Array<Omit<WorkItem,'id'>>=[]; let restricted=false; for(const repository of repositories) { try { const [prs, issues]=await Promise.all([this.request<Array<{number:number;title:string;html_url:string;updated_at:string;user:{login:string};head:{sha:string};requested_reviewers:Array<{login:string}>}>>(`/repos/${repository}/pulls?state=open&per_page=100`,token),this.request<Array<{number:number;title:string;html_url:string;updated_at:string;pull_request?:unknown}>>(`/repos/${repository}/issues?state=open&assignee=${encodeURIComponent(user.login)}&per_page=100`,token)]); for(const pr of prs) { const review=pr.requested_reviewers.some((reviewer)=>reviewer.login===user.login); const authored=pr.user.login===user.login; const failed=authored && (await this.request<{check_runs:Array<{conclusion:string|null}>}>(`/repos/${repository}/commits/${pr.head.sha}/check-runs`,token)).check_runs.some((check)=>['failure','timed_out','cancelled','action_required'].includes(check.conclusion??'')); if(authored&&failed) items.push({repository,title:pr.title,reason:'CI failing on your PR',priority:'urgent',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}); else if(review) items.push({repository,title:pr.title,reason:'Review requested from you',priority:'high',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}); else if(authored) items.push({repository,title:pr.title,reason:'Open PR authored by you',priority:'normal',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}) } for(const issue of issues) if(!issue.pull_request) items.push({repository,title:issue.title,reason:'Issue assigned to you',priority:'normal',url:issue.html_url,updatedAt:issue.updated_at,kind:'issue'}) } catch(error) { if(error instanceof GitHubApiError&&error.status===451) { restricted=true; continue } throw error } } this.store.replaceWorkspaceGitHubWork(workspaceId,items); this.store.markGlobalSynced(integration.id); if(restricted) this.store.globalIntegrationWarning(integration.id,'Some GitHub sources are unavailable from this network or region (HTTP 451). Other available sources were synced.') } catch(error) { const message=error instanceof Error?error.message:'GitHub sync failed.'; this.store.globalIntegrationError(integration.id,message.includes('401')?'needs_reauth':'error',message); throw error } }
  private async listBackupRepositories(token: string): Promise<BackupRepository[]> { const repositories=await this.request<Array<{id:number;full_name:string;private:boolean;default_branch:string;permissions?:{push?:boolean;admin?:boolean;maintain?:boolean}}>>('/user/repos?per_page=100&affiliation=owner,collaborator,organization_member',token); return repositories.filter((repository)=>repository.private && !!(repository.permissions?.push||repository.permissions?.admin||repository.permissions?.maintain)).map((repository)=>({id:repository.id,fullName:repository.full_name,defaultBranch:repository.default_branch})) }
  private async repositoryCount(owner: Pick<GitHubRepositoryOwner,'login'|'kind'>, token:string): Promise<number> { const path=owner.kind==='user' ? '/user/repos?affiliation=owner&per_page=1' : `/orgs/${encodeURIComponent(owner.login)}/repos?type=all&per_page=1`; const response=await this.response(path,token); const body=await response.json() as unknown[]; const link=response.headers.get('link') ?? ''; const last=link.match(/[?&]page=(\d+)[^>]*>; rel="last"/); return last ? Number(last[1]) : body.length }
  private async listRepositoryNames(path:string, token:string): Promise<string[]> { const repositories: string[]=[]; for(let page=1;;page++){const separator=path.includes('?')?'&':'?'; const result=await this.request<Array<{full_name:string}>>(`${path}${separator}page=${page}`,token); repositories.push(...result.map((repository)=>repository.full_name)); if(result.length<100) return [...new Set(repositories)]} }
  private token(): string { const backupToken=this.store.backupToken(); if(backupToken) return this.vault.decrypt(backupToken); const integration=this.store.globalGitHub(); if(!integration) throw new Error('Connect GitHub or add a backup token first.'); return this.vault.decrypt(this.store.globalToken(integration.id)) }
  private backupError(error: unknown): string { if(error instanceof GitHubApiError) { if(error.status===401) return 'GitHub authorization expired. Reconnect GitHub and try again.'; if(error.status===403) return 'GitHub denied access to this backup repository.'; if(error.status===404) return 'No DevBox backup exists in this repository yet.'; if(error.status===409||error.status===422) return 'The backup changed on GitHub. Try backing up again.'; return `GitHub backup failed (HTTP ${error.status}).` } return error instanceof Error ? error.message : 'GitHub backup failed.' }
  private async response(path:string,token:string,init:RequestInit={}): Promise<Response> { const response=await fetch(`${API}${path}`,{...init,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...init.headers}}); if (!response.ok) throw new GitHubApiError(response.status); return response }
  private async request<T>(path:string,token:string,init:RequestInit={}): Promise<T> { return (await this.response(path,token,init)).json() as Promise<T> }
}
