import { DevBoxStore } from './storage'
import { TokenVault } from './security'
import type { BackupRepository, BackupStatus, WorkItem } from '../shared/contracts'
const API = 'https://api.github.com'
const BACKUP_PATH = 'devbox-backup/v1/latest.json'
class GitHubApiError extends Error { constructor(readonly status: number) { super(`GitHub API ${status}`) } }
export class GitHubService {
  constructor(private store: DevBoxStore, private vault = new TokenVault()) {}
  async connectPersonalAccessToken(token: string): Promise<void> { const value=token.trim(); if (!value) throw new Error('Enter a GitHub personal access token.'); const user=await this.request<{login:string}>('/user',value); const repos=await this.request<Array<{full_name:string}>>('/user/repos?per_page=100&affiliation=owner,collaborator,organization_member',value); const id=this.store.createGlobalGitHub(user.login,this.vault.encrypt(value),repos.map((repo)=>repo.full_name)); this.store.markGlobalSynced(id) }
  async refreshGlobal(): Promise<void> { const integration=this.store.globalGitHub(); if (!integration) throw new Error('GitHub is not connected.'); try { await this.request('/user',this.vault.decrypt(this.store.globalToken(integration.id))); this.store.markGlobalSynced(integration.id) } catch(error) { const message=error instanceof Error?error.message:'GitHub sync failed.'; this.store.globalIntegrationError(integration.id,message.includes('401')?'needs_reauth':'error',message); throw error } }
  async backupRepositories(): Promise<BackupRepository[]> { const token=this.token(); const repositories=await this.request<Array<{id:number;full_name:string;private:boolean;default_branch:string;permissions?:{push?:boolean;admin?:boolean;maintain?:boolean}}>>('/user/repos?per_page=100&affiliation=owner,collaborator,organization_member',token); return repositories.filter((repository)=>repository.private && !!(repository.permissions?.push||repository.permissions?.admin||repository.permissions?.maintain)).map((repository)=>({id:repository.id,fullName:repository.full_name,defaultBranch:repository.default_branch})) }
  async configureBackup(repositoryId: number): Promise<BackupStatus> { const repository=(await this.backupRepositories()).find((item)=>item.id===repositoryId); if(!repository) throw new Error('Choose a private repository you can push to.'); return this.store.configureBackup(repository) }
  async backupNow(): Promise<BackupStatus> { const status=this.store.backupStatus(); if(!status.repository) throw new Error('Choose a private backup repository first.'); try { const token=this.token(); const content=Buffer.from(JSON.stringify(this.store.backupSnapshot(),null,2)).toString('base64'); let sha: string|undefined; try { const existing=await this.request<{sha:string}>(`/repos/${status.repository.fullName}/contents/${BACKUP_PATH}?ref=${encodeURIComponent(status.repository.defaultBranch)}`,token); sha=existing.sha } catch(error) { if(!(error instanceof GitHubApiError && error.status===404)) throw error } const result=await this.request<{commit:{html_url:string}>(`/repos/${status.repository.fullName}/contents/${BACKUP_PATH}`,token,{method:'PUT',body:JSON.stringify({message:'DevBox backup',content,branch:status.repository.defaultBranch,...(sha?{sha}:{})})}); this.store.markBackupSuccess(result.commit.html_url); return this.store.backupStatus() } catch(error) { const message=this.backupError(error); this.store.markBackupFailure(message); throw new Error(message) } }
  async restoreLatest(): Promise<void> { const status=this.store.backupStatus(); if(!status.repository) throw new Error('Choose a private backup repository first.'); try { const content=await this.request<{content:string;encoding:string}>(`/repos/${status.repository.fullName}/contents/${BACKUP_PATH}?ref=${encodeURIComponent(status.repository.defaultBranch)}`,this.token()); if(content.encoding!=='base64') throw new Error('Backup content encoding is not supported.'); this.store.restoreBackup(JSON.parse(Buffer.from(content.content.replace(/\n/g,''),'base64').toString('utf8'))) } catch(error) { throw new Error(this.backupError(error)) } }
  async sync(id: string): Promise<void> { const integration=this.store.integration(id); try { const token=this.vault.decrypt(this.store.getToken(id)); const user=await this.request<{login:string}>('/user',token); const items: Array<Omit<WorkItem,'id'>>=[]; let restricted=false; for (const repo of integration.repositories) { try { const prs=await this.request<Array<{number:number;title:string;html_url:string;updated_at:string;user:{login:string};head:{sha:string};requested_reviewers:Array<{login:string}>}>>(`/repos/${repo}/pulls?state=open&per_page=100`,token); for (const pr of prs) { const checks=await this.request<{check_runs:Array<{conclusion:string|null}>}>(`/repos/${repo}/commits/${pr.head.sha}/check-runs`,token); const failed=checks.check_runs.some((check)=>['failure','timed_out','cancelled','action_required'].includes(check.conclusion ?? '')); const review=pr.requested_reviewers.some((reviewer)=>reviewer.login===user.login); if (pr.user.login===user.login && failed) items.push({title:pr.title,reason:'CI failing on your PR',priority:'urgent',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}); else if (review) items.push({title:pr.title,reason:'Review requested from you',priority:'high',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}); else if (pr.user.login===user.login) items.push({title:pr.title,reason:'Open PR authored by you',priority:'normal',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}) } } catch (error) { if (error instanceof GitHubApiError && error.status === 451) { restricted=true; continue } throw error } } try { const notifications=await this.request<Array<{id:string;subject:{title:string;url:string|null};updated_at:string;reason:string;repository:{html_url:string}}>>('/notifications?participating=false&per_page=100',token); for (const n of notifications.filter((x)=>['mention','review_requested'].includes(x.reason))) items.push({title:n.subject.title,reason:n.reason==='mention'?'Mentioned on GitHub':'Review requested from you',priority:'high',url:n.subject.url?.replace(API,'https://github.com') ?? n.repository.html_url,updatedAt:n.updated_at,kind:'notification'}) } catch (error) { if (error instanceof GitHubApiError && error.status === 451) restricted=true; else throw error } this.store.replaceGitHubWork(id,items); if (restricted) this.store.markIntegrationWarning(id,'Some GitHub sources are unavailable from this network or region (HTTP 451). Other available sources were synced.') } catch (error) { const message=error instanceof Error?error.message:'GitHub sync failed.'; this.store.markIntegrationError(id,message.includes('401')?'needs_reauth':'error',message); throw error } }
  private token(): string { const integration=this.store.globalGitHub(); if(!integration) throw new Error('Connect GitHub before using backups.'); return this.vault.decrypt(this.store.globalToken(integration.id)) }
  private backupError(error: unknown): string { if(error instanceof GitHubApiError) { if(error.status===401) return 'GitHub authorization expired. Reconnect GitHub and try again.'; if(error.status===403) return 'GitHub denied access to this backup repository.'; if(error.status===404) return 'No DevBox backup exists in this repository yet.'; if(error.status===409||error.status===422) return 'The backup changed on GitHub. Try backing up again.'; return `GitHub backup failed (HTTP ${error.status}).` } return error instanceof Error ? error.message : 'GitHub backup failed.' }
  private async request<T>(path:string,token:string,init:RequestInit={}): Promise<T> { const response=await fetch(`${API}${path}`,{...init,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...init.headers}}); if (!response.ok) throw new GitHubApiError(response.status); return response.json() as Promise<T> }
}
