import { shell } from 'electron'
import { DevBoxStore } from './storage'
import { TokenVault } from './security'
import type { WorkItem } from '../shared/contracts'
const API = 'https://api.github.com'
type Pending = { deviceCode:string; expiresAt:number }
export class GitHubService {
  private pending = new Map<string, Pending>()
  constructor(private store: DevBoxStore, private clientId: string | undefined, private vault = new TokenVault()) {}
  async begin(workspaceId: string): Promise<{userCode:string; verificationUri:string}> { if (!this.clientId) throw new Error('DEVBOX_GITHUB_CLIENT_ID is not configured.'); const response = await fetch('https://github.com/login/device/code',{method:'POST',headers:{Accept:'application/json'},body:new URLSearchParams({client_id:this.clientId,scope:'read:user repo notifications'})}); if (!response.ok) throw new Error('GitHub device authorization could not be started.'); const body = await response.json() as {device_code:string;user_code:string;verification_uri:string;expires_in:number}; this.pending.set(workspaceId,{deviceCode:body.device_code,expiresAt:Date.now()+body.expires_in*1000}); await shell.openExternal(body.verification_uri); return {userCode:body.user_code,verificationUri:body.verification_uri} }
  async complete(workspaceId: string): Promise<void> { const pending=this.pending.get(workspaceId); if (!pending || pending.expiresAt<Date.now()) throw new Error('Start GitHub authorization again.'); if (!this.clientId) throw new Error('DEVBOX_GITHUB_CLIENT_ID is not configured.'); const response=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json'},body:new URLSearchParams({client_id:this.clientId,device_code:pending.deviceCode,grant_type:'urn:ietf:params:oauth:grant-type:device_code'})}); const token=await response.json() as {access_token?:string;error?:string}; if (!token.access_token) throw new Error(token.error === 'authorization_pending' ? 'Authorization is still pending.' : 'GitHub authorization failed.'); const user=await this.request<{login:string}>('/user',token.access_token); const repos=await this.request<Array<{full_name:string}>>('/user/repos?per_page=100&affiliation=owner,collaborator,organization_member',token.access_token); const id=this.store.createGitHubIntegration(workspaceId,user.login,this.vault.encrypt(token.access_token),repos.map((repo)=>repo.full_name)); this.pending.delete(workspaceId); await this.sync(id) }
  async sync(id: string): Promise<void> { const integration=this.store.integration(id); try { const token=this.vault.decrypt(this.store.getToken(id)); const user=await this.request<{login:string}>('/user',token); const items: Array<Omit<WorkItem,'id'>>=[]; for (const repo of integration.repositories) { const prs=await this.request<Array<{number:number;title:string;html_url:string;updated_at:string;user:{login:string};head:{sha:string};requested_reviewers:Array<{login:string}>}>>(`/repos/${repo}/pulls?state=open&per_page=100`,token); for (const pr of prs) { const checks=await this.request<{check_runs:Array<{conclusion:string|null}>}>(`/repos/${repo}/commits/${pr.head.sha}/check-runs`,token); const failed=checks.check_runs.some((check)=>['failure','timed_out','cancelled','action_required'].includes(check.conclusion ?? '')); const review=pr.requested_reviewers.some((reviewer)=>reviewer.login===user.login); if (pr.user.login===user.login && failed) items.push({title:pr.title,reason:'CI failing on your PR',priority:'urgent',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}); else if (review) items.push({title:pr.title,reason:'Review requested from you',priority:'high',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}); else if (pr.user.login===user.login) items.push({title:pr.title,reason:'Open PR authored by you',priority:'normal',url:pr.html_url,updatedAt:pr.updated_at,kind:'pr'}) } } const notifications=await this.request<Array<{id:string;subject:{title:string;url:string|null};updated_at:string;reason:string;repository:{html_url:string}}>>('/notifications?participating=false&per_page=100',token); for (const n of notifications.filter((x)=>['mention','review_requested'].includes(x.reason))) items.push({title:n.subject.title,reason:n.reason==='mention'?'Mentioned on GitHub':'Review requested from you',priority:'high',url:n.subject.url?.replace(API,'https://github.com') ?? n.repository.html_url,updatedAt:n.updated_at,kind:'notification'}); this.store.replaceGitHubWork(id,items) } catch (error) { const message=error instanceof Error?error.message:'GitHub sync failed.'; this.store.markIntegrationError(id,message.includes('401')?'needs_reauth':'error',message); throw error } }
  private async request<T>(path:string,token:string): Promise<T> { const response=await fetch(`${API}${path}`,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28'}}); if (!response.ok) throw new Error(`GitHub API ${response.status}`); return response.json() as Promise<T> }
}
