import Database from 'better-sqlite3'
import { mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { randomUUID } from 'node:crypto'
import type { Workspace, WorkspaceSummary } from '../shared/contracts'
import type { BackupRepository, BackupStatus, IntegrationSummary, WorkItem } from '../shared/contracts'

type Row = { id: string; name: string; created_at: string; updated_at: string; last_opened_at: string }
type BackupSnapshot = { format: 'devbox-backup'; version: 1; createdAt: string; data: Record<string, unknown[]> }
const map = (row: Row): Workspace => ({ id: row.id, name: row.name, createdAt: row.created_at, updatedAt: row.updated_at, lastOpenedAt: row.last_opened_at })

export class DevBoxStore {
  private db: Database.Database
  constructor(path: string) { mkdirSync(dirname(path), { recursive: true }); this.db = new Database(path); this.migrate() }
  private migrate(): void {
    this.db.exec(`PRAGMA foreign_keys = ON;
      CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL COLLATE NOCASE UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, last_opened_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS preferences (workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, key TEXT NOT NULL, value_json TEXT NOT NULL, PRIMARY KEY(workspace_id,key));
      CREATE TABLE IF NOT EXISTS integrations (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, provider TEXT NOT NULL, state TEXT NOT NULL, display_name TEXT, config_json TEXT NOT NULL DEFAULT '{}', last_synced_at TEXT, last_error TEXT);
      CREATE TABLE IF NOT EXISTS source_entities (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, integration_id TEXT REFERENCES integrations(id) ON DELETE CASCADE, provider TEXT NOT NULL, provider_id TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, url TEXT NOT NULL, status TEXT, updated_at TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}', UNIQUE(integration_id, provider_id, type));
      CREATE TABLE IF NOT EXISTS secret_references (integration_id TEXT PRIMARY KEY REFERENCES integrations(id) ON DELETE CASCADE, encrypted_blob BLOB NOT NULL);
      CREATE TABLE IF NOT EXISTS work_items (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, integration_id TEXT NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, source_entity_id TEXT NOT NULL REFERENCES source_entities(id) ON DELETE CASCADE, title TEXT NOT NULL, reason TEXT NOT NULL, priority TEXT NOT NULL, url TEXT NOT NULL, kind TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(integration_id, source_entity_id));
      CREATE TABLE IF NOT EXISTS app_state (key TEXT PRIMARY KEY, value TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS global_integrations (id TEXT PRIMARY KEY, provider TEXT NOT NULL UNIQUE, state TEXT NOT NULL, display_name TEXT NOT NULL, repositories_json TEXT NOT NULL, last_synced_at TEXT, last_error TEXT);
      CREATE TABLE IF NOT EXISTS global_secret_references (integration_id TEXT PRIMARY KEY REFERENCES global_integrations(id) ON DELETE CASCADE, encrypted_blob BLOB NOT NULL);
      CREATE TABLE IF NOT EXISTS workspace_repository_assignments (workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, integration_id TEXT NOT NULL REFERENCES global_integrations(id) ON DELETE CASCADE, repository_full_name TEXT NOT NULL, PRIMARY KEY(workspace_id,integration_id,repository_full_name));
      CREATE TABLE IF NOT EXISTS github_workspace_items (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, repository_full_name TEXT NOT NULL, provider_id TEXT NOT NULL, title TEXT NOT NULL, reason TEXT NOT NULL, priority TEXT NOT NULL, url TEXT NOT NULL, kind TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(workspace_id,repository_full_name,provider_id,kind));
      CREATE TABLE IF NOT EXISTS archived_workspaces (workspace_id TEXT PRIMARY KEY REFERENCES workspaces(id) ON DELETE CASCADE, archived_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS backup_config (id INTEGER PRIMARY KEY CHECK(id=1), repository_id INTEGER NOT NULL, repository_full_name TEXT NOT NULL, default_branch TEXT NOT NULL, last_backed_up_at TEXT, last_commit_url TEXT, last_error TEXT, dirty INTEGER NOT NULL DEFAULT 1);`)
    this.migrateGitHubToGlobal()
  }
  private migrateGitHubToGlobal(): void { const existing=this.db.prepare("SELECT id FROM global_integrations WHERE provider='github'").get(); if (existing) return; const legacy=this.db.prepare("SELECT * FROM integrations WHERE provider='github' ORDER BY rowid").all() as Array<{id:string;workspace_id:string;display_name:string;config_json:string}>; const source=legacy[0]; if (!source || legacy.length !== 1) return; const secret=this.db.prepare('SELECT encrypted_blob FROM secret_references WHERE integration_id=?').get(source.id) as {encrypted_blob:Buffer}|undefined; if (!secret) return; const repos=(JSON.parse(source.config_json) as {repositories:string[]}).repositories; const id=randomUUID(); this.db.prepare("INSERT INTO global_integrations VALUES (?, 'github', 'connected', ?, ?, NULL, NULL)").run(id,source.display_name,JSON.stringify(repos)); this.db.prepare('INSERT INTO global_secret_references VALUES (?,?)').run(id,secret.encrypted_blob); const add=this.db.prepare('INSERT OR IGNORE INTO workspace_repository_assignments VALUES (?,?,?)'); for (const repository of repos) add.run(source.workspace_id,id,repository) }
  createWorkspace(rawName: string): Workspace { const name = validateName(rawName); const now = new Date().toISOString(); const workspace = { id: randomUUID(), name, createdAt: now, updatedAt: now, lastOpenedAt: now }; this.db.prepare('INSERT INTO workspaces VALUES (@id,@name,@createdAt,@updatedAt,@lastOpenedAt)').run(workspace); this.selectWorkspace(workspace.id); this.markBackupDirty(); return workspace }
  listWorkspaces(): WorkspaceSummary[] { return this.db.prepare(`SELECT w.*, count(DISTINCT a.integration_id) integration_count FROM workspaces w LEFT JOIN workspace_repository_assignments a ON a.workspace_id=w.id LEFT JOIN archived_workspaces aw ON aw.workspace_id=w.id WHERE aw.workspace_id IS NULL GROUP BY w.id ORDER BY w.last_opened_at DESC`).all().map((r) => ({ ...map(r as Row), integrationCount: Number((r as { integration_count: number }).integration_count) })) }
  getWorkspace(id: string): Workspace | null { const row = this.db.prepare('SELECT * FROM workspaces WHERE id=?').get(id) as Row | undefined; return row ? map(row) : null }
  currentWorkspace(): Workspace | null { const current = this.db.prepare("SELECT value FROM app_state WHERE key='current_workspace_id'").get() as { value: string } | undefined; return current ? this.getWorkspace(current.value) : null }
  selectWorkspace(id: string): Workspace { const workspace = this.require(id); const now = new Date().toISOString(); this.db.prepare('UPDATE workspaces SET last_opened_at=?, updated_at=? WHERE id=?').run(now, now, id); this.db.prepare("INSERT INTO app_state(key,value) VALUES ('current_workspace_id',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(id); return { ...workspace, updatedAt: now, lastOpenedAt: now } }
  renameWorkspace(id: string, rawName: string): Workspace { this.require(id); const name = validateName(rawName); const now = new Date().toISOString(); this.db.prepare('UPDATE workspaces SET name=?, updated_at=? WHERE id=?').run(name, now, id); this.markBackupDirty(); return { ...this.require(id), name, updatedAt: now } }
  deleteWorkspace(id: string, confirmationName: string): void { const workspace = this.require(id); if (workspace.name !== confirmationName.trim()) throw new Error('Workspace name does not match confirmation.'); this.db.prepare('DELETE FROM workspaces WHERE id=?').run(id); if (this.currentWorkspace()?.id === id) this.db.prepare("DELETE FROM app_state WHERE key='current_workspace_id'").run(); this.markBackupDirty() }
  archiveWorkspace(id: string): void { this.require(id); this.db.prepare('INSERT OR REPLACE INTO archived_workspaces VALUES (?,?)').run(id,new Date().toISOString()); if(this.currentWorkspace()?.id===id){const next=this.listWorkspaces()[0]; if(next) this.selectWorkspace(next.id); else this.db.prepare("DELETE FROM app_state WHERE key='current_workspace_id'").run()}; this.markBackupDirty() }
  getTheme(workspaceId: string): 'dark' | 'light' | 'system' { this.require(workspaceId); const r = this.db.prepare("SELECT value_json FROM preferences WHERE workspace_id=? AND key='theme'").get(workspaceId) as { value_json: string } | undefined; return r ? JSON.parse(r.value_json) : 'dark' }
  setTheme(workspaceId: string, value: 'dark' | 'light' | 'system'): void { this.require(workspaceId); this.db.prepare("INSERT INTO preferences VALUES (?, 'theme', ?) ON CONFLICT(workspace_id,key) DO UPDATE SET value_json=excluded.value_json").run(workspaceId, JSON.stringify(value)); this.markBackupDirty() }
  createGitHubIntegration(workspaceId: string, displayName: string, token: Buffer, repositories: string[]): string { this.require(workspaceId); this.removeGitHub(workspaceId); const id = randomUUID(); this.db.prepare('INSERT INTO integrations(id,workspace_id,provider,state,display_name,config_json) VALUES (?,?,\'github\',\'connected\',?,?)').run(id, workspaceId, displayName, JSON.stringify({ repositories })); this.db.prepare('INSERT INTO secret_references VALUES (?,?)').run(id, token); return id }
  getToken(id: string): Buffer { const row = this.db.prepare('SELECT encrypted_blob FROM secret_references WHERE integration_id=?').get(id) as { encrypted_blob: Buffer } | undefined; if (!row) throw new Error('GitHub credentials are unavailable.'); return row.encrypted_blob }
  githubIntegrations(workspaceId: string): IntegrationSummary[] { this.require(workspaceId); return this.db.prepare("SELECT * FROM integrations WHERE workspace_id=? AND provider='github'").all(workspaceId).map((r) => { const x = r as { id:string; state:IntegrationSummary['state']; display_name:string; last_synced_at:string|null; last_error:string|null; config_json:string }; const config = JSON.parse(x.config_json) as { repositories:string[] }; return { id:x.id, provider:'github', state:x.state, displayName:x.display_name, lastSyncedAt:x.last_synced_at, lastError:x.last_error, repositories:config.repositories.map((fullName) => ({ fullName, selected:true })) } }) }
  setRepositories(id: string, repositories: string[]): void { this.db.prepare('UPDATE integrations SET config_json=? WHERE id=? AND provider=\'github\'').run(JSON.stringify({ repositories }), id) }
  integration(id: string): { id:string; workspaceId:string; repositories:string[] } { const x = this.db.prepare("SELECT id,workspace_id,config_json FROM integrations WHERE id=? AND provider='github'").get(id) as { id:string; workspace_id:string; config_json:string } | undefined; if (!x) throw new Error('GitHub integration not found.'); return { id:x.id, workspaceId:x.workspace_id, repositories:(JSON.parse(x.config_json) as {repositories:string[]}).repositories } }
  removeGitHub(workspaceId: string): void { this.db.prepare("DELETE FROM integrations WHERE workspace_id=? AND provider='github'").run(workspaceId) }
  replaceGitHubWork(id: string, items: Array<Omit<WorkItem, 'id'>>): void { const integration = this.integration(id); const transaction = this.db.transaction(() => { this.db.prepare('DELETE FROM work_items WHERE integration_id=?').run(id); this.db.prepare('DELETE FROM source_entities WHERE integration_id=?').run(id); for (const item of items) { const sourceId = randomUUID(); this.db.prepare('INSERT INTO source_entities(id,workspace_id,integration_id,provider,provider_id,type,title,url,status,updated_at,payload_json) VALUES (?,?,?,?,?,?,?,?,?,?,\'{}\')').run(sourceId,integration.workspaceId,id,'github',item.url,item.kind,item.title,item.url,item.priority,item.updatedAt); this.db.prepare('INSERT INTO work_items VALUES (?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),integration.workspaceId,id,sourceId,item.title,item.reason,item.priority,item.url,item.kind,item.updatedAt) } this.db.prepare('UPDATE integrations SET last_synced_at=?,last_error=NULL WHERE id=?').run(new Date().toISOString(),id) }); transaction(); this.markBackupDirty() }
  markIntegrationError(id: string, state: 'needs_reauth' | 'error', error: string): void { this.db.prepare('UPDATE integrations SET state=?,last_error=? WHERE id=?').run(state,error,id) }
  markIntegrationWarning(id: string, warning: string): void { this.db.prepare("UPDATE integrations SET state='connected',last_error=? WHERE id=?").run(warning,id) }
  globalGitHub(): {id:string;displayName:string;state:IntegrationSummary['state'];repositories:string[];lastSyncedAt:string|null;lastError:string|null}|null { const x=this.db.prepare("SELECT * FROM global_integrations WHERE provider='github'").get() as {id:string;display_name:string;state:IntegrationSummary['state'];repositories_json:string;last_synced_at:string|null;last_error:string|null}|undefined; return x ? {id:x.id,displayName:x.display_name,state:x.state,repositories:JSON.parse(x.repositories_json),lastSyncedAt:x.last_synced_at,lastError:x.last_error}:null }
  createGlobalGitHub(displayName:string, token:Buffer, repositories:string[]): string { this.db.prepare("DELETE FROM global_integrations WHERE provider='github'").run(); const id=randomUUID(); this.db.prepare("INSERT INTO global_integrations VALUES (?, 'github', 'connected', ?, ?, NULL, NULL)").run(id,displayName,JSON.stringify(repositories)); this.db.prepare('INSERT INTO global_secret_references VALUES (?,?)').run(id,token); this.markBackupDirty(); return id }
  updateGlobalGitHubRepositories(id:string, repositories:string[]): void { const unique=[...new Set(repositories)]; const transaction=this.db.transaction(()=>{this.db.prepare("UPDATE global_integrations SET repositories_json=? WHERE id=? AND provider='github'").run(JSON.stringify(unique),id); if(unique.length===0) { this.db.prepare('DELETE FROM workspace_repository_assignments WHERE integration_id=?').run(id); this.db.prepare('DELETE FROM github_workspace_items').run() } else { this.db.prepare(`DELETE FROM workspace_repository_assignments WHERE integration_id=? AND repository_full_name NOT IN (${unique.map(()=>'?').join(',')})`).run(id,...unique); this.db.prepare('DELETE FROM github_workspace_items WHERE NOT EXISTS (SELECT 1 FROM workspace_repository_assignments a WHERE a.workspace_id=github_workspace_items.workspace_id AND a.repository_full_name=github_workspace_items.repository_full_name)').run() }}); transaction(); this.markBackupDirty() }
  globalToken(id:string): Buffer { const x=this.db.prepare('SELECT encrypted_blob FROM global_secret_references WHERE integration_id=?').get(id) as {encrypted_blob:Buffer}|undefined; if(!x) throw new Error('GitHub credentials are unavailable.'); return x.encrypted_blob }
  assignedRepositories(workspaceId:string): string[] { return this.db.prepare('SELECT repository_full_name FROM workspace_repository_assignments WHERE workspace_id=?').all(workspaceId).map((x)=> (x as {repository_full_name:string}).repository_full_name) }
  setAssignedRepositories(workspaceId:string, repositories:string[]): void { this.require(workspaceId); const global=this.globalGitHub(); if(!global) throw new Error('Connect GitHub first.'); const unique=[...new Set(repositories)]; if(unique.length>5) throw new Error('A workspace can have at most 5 GitHub repositories.'); const allowed=new Set(global.repositories); if(unique.some((x)=>!allowed.has(x))) throw new Error('A selected repository is not available to this GitHub account.'); const transaction=this.db.transaction(()=>{this.db.prepare('DELETE FROM workspace_repository_assignments WHERE workspace_id=? AND integration_id=?').run(workspaceId,global.id); const add=this.db.prepare('INSERT INTO workspace_repository_assignments VALUES (?,?,?)'); for(const repository of unique) add.run(workspaceId,global.id,repository); if(unique.length===0) this.db.prepare('DELETE FROM github_workspace_items WHERE workspace_id=?').run(workspaceId); else this.db.prepare(`DELETE FROM github_workspace_items WHERE workspace_id=? AND repository_full_name NOT IN (${unique.map(()=>'?').join(',')})`).run(workspaceId,...unique)}); transaction(); this.markBackupDirty() }
  replaceWorkspaceGitHubWork(workspaceId:string, items:Array<Omit<WorkItem,'id'>>): void { this.require(workspaceId); const transaction=this.db.transaction(()=>{this.db.prepare('DELETE FROM github_workspace_items WHERE workspace_id=?').run(workspaceId); const add=this.db.prepare('INSERT INTO github_workspace_items VALUES (?,?,?,?,?,?,?,?,?,?)'); for(const item of items) add.run(randomUUID(),workspaceId,item.repository,item.url,item.title,item.reason,item.priority,item.url,item.kind,item.updatedAt)}); transaction(); this.markBackupDirty() }
  globalIntegrationError(id:string,state:'needs_reauth'|'error',error:string):void { this.db.prepare('UPDATE global_integrations SET state=?,last_error=? WHERE id=?').run(state,error,id) }
  globalIntegrationWarning(id:string,warning:string):void { this.db.prepare("UPDATE global_integrations SET state='connected',last_error=? WHERE id=?").run(warning,id) }
  markGlobalSynced(id:string):void { this.db.prepare("UPDATE global_integrations SET state='connected',last_synced_at=?,last_error=NULL WHERE id=?").run(new Date().toISOString(),id) }
  removeGlobalGitHub():void { this.db.prepare("DELETE FROM global_integrations WHERE provider='github'").run(); this.markBackupDirty() }
  backupStatus(): BackupStatus { const row=this.db.prepare('SELECT * FROM backup_config WHERE id=1').get() as {repository_id:number;repository_full_name:string;default_branch:string;last_backed_up_at:string|null;last_commit_url:string|null;last_error:string|null;dirty:number}|undefined; return row ? {repository:{id:row.repository_id,fullName:row.repository_full_name,defaultBranch:row.default_branch},lastBackedUpAt:row.last_backed_up_at,lastCommitUrl:row.last_commit_url,lastError:row.last_error,dirty:!!row.dirty}:{repository:null,lastBackedUpAt:null,lastCommitUrl:null,lastError:null,dirty:false} }
  configureBackup(repository: BackupRepository): BackupStatus { this.db.prepare('INSERT INTO backup_config(id,repository_id,repository_full_name,default_branch,dirty) VALUES (1,?,?,?,1) ON CONFLICT(id) DO UPDATE SET repository_id=excluded.repository_id,repository_full_name=excluded.repository_full_name,default_branch=excluded.default_branch,last_error=NULL,dirty=1').run(repository.id,repository.fullName,repository.defaultBranch); return this.backupStatus() }
  markBackupSuccess(commitUrl: string): void { this.db.prepare('UPDATE backup_config SET last_backed_up_at=?,last_commit_url=?,last_error=NULL,dirty=0 WHERE id=1').run(new Date().toISOString(),commitUrl) }
  markBackupFailure(message: string): void { this.db.prepare('UPDATE backup_config SET last_error=? WHERE id=1').run(message) }
  backupSnapshot(): BackupSnapshot { const tables=['workspaces','preferences','integrations','source_entities','work_items','app_state','global_integrations','workspace_repository_assignments','archived_workspaces']; const data=Object.fromEntries(tables.map((table)=>[table,this.db.prepare(`SELECT * FROM ${table}`).all()])); return {format:'devbox-backup',version:1,createdAt:new Date().toISOString(),data} }
  restoreBackup(snapshot: unknown): void { const parsed=this.parseBackup(snapshot); const data=parsed.data; const rows=(name:string): unknown[] => data[name] ?? []; const transaction=this.db.transaction(()=>{ for(const table of ['work_items','source_entities','secret_references','workspace_repository_assignments','global_secret_references','archived_workspaces','preferences','integrations','global_integrations','app_state','workspaces']) this.db.prepare(`DELETE FROM ${table}`).run(); const insert=(table:string, columns:string[])=>{const values=rows(table); if(!values.length) return; const statement=this.db.prepare(`INSERT INTO ${table} (${columns.join(',')}) VALUES (${columns.map((x)=>'@'+x).join(',')})`); for(const value of values) statement.run(value as Record<string,unknown>)}; insert('workspaces',['id','name','created_at','updated_at','last_opened_at']); insert('preferences',['workspace_id','key','value_json']); insert('integrations',['id','workspace_id','provider','state','display_name','config_json','last_synced_at','last_error']); insert('source_entities',['id','workspace_id','integration_id','provider','provider_id','type','title','url','status','updated_at','payload_json']); insert('work_items',['id','workspace_id','integration_id','source_entity_id','title','reason','priority','url','kind','updated_at']); insert('global_integrations',['id','provider','state','display_name','repositories_json','last_synced_at','last_error']); insert('workspace_repository_assignments',['workspace_id','integration_id','repository_full_name']); insert('archived_workspaces',['workspace_id','archived_at']); insert('app_state',['key','value']); this.db.prepare("UPDATE integrations SET state='needs_reauth',last_error='Reconnect GitHub after restoring this backup.' WHERE provider='github'").run(); this.db.prepare("UPDATE global_integrations SET state='needs_reauth',last_error='Reconnect GitHub after restoring this backup.' WHERE provider='github'").run(); }); transaction(); this.markBackupDirty() }
  private parseBackup(value: unknown): BackupSnapshot { if(!value || typeof value!=='object') throw new Error('Backup is not valid JSON.'); const snapshot=value as Partial<BackupSnapshot>; if(snapshot.format!=='devbox-backup'||snapshot.version!==1||!snapshot.data||typeof snapshot.data!=='object') throw new Error('Backup format or version is not supported.'); for(const [table,rows] of Object.entries(snapshot.data)) if(!Array.isArray(rows)) throw new Error(`Backup table ${table} is invalid.`); return snapshot as BackupSnapshot }
  private markBackupDirty(): void { this.db.prepare('UPDATE backup_config SET dirty=1 WHERE id=1').run() }
  workItems(workspaceId: string): WorkItem[] { return this.db.prepare('SELECT id,repository_full_name,title,reason,priority,url,updated_at,kind FROM github_workspace_items WHERE workspace_id=? ORDER BY CASE priority WHEN \'urgent\' THEN 0 WHEN \'high\' THEN 1 ELSE 2 END, updated_at DESC').all(workspaceId).map((r) => { const x=r as {id:string;repository_full_name:string;title:string;reason:string;priority:WorkItem['priority'];url:string;updated_at:string;kind:WorkItem['kind']}; return {id:x.id,repository:x.repository_full_name,title:x.title,reason:x.reason,priority:x.priority,url:x.url,updatedAt:x.updated_at,kind:x.kind} }) }
  close(): void { this.db.close() }
  private require(id: string): Workspace { const workspace = this.getWorkspace(id); if (!workspace) throw new Error('Workspace not found.'); return workspace }
}
export function validateName(value: string): string { const name = value.trim(); if (!name || name.length > 80) throw new Error('Workspace name must be between 1 and 80 characters.'); return name }
