import Database from 'better-sqlite3'
import { mkdirSync } from 'node:fs'
import { dirname } from 'node:path'
import { randomUUID } from 'node:crypto'
import type { Workspace, WorkspaceSummary } from '../shared/contracts'
import type { IntegrationSummary, WorkItem } from '../shared/contracts'

type Row = { id: string; name: string; created_at: string; updated_at: string; last_opened_at: string }
const map = (row: Row): Workspace => ({ id: row.id, name: row.name, createdAt: row.created_at, updatedAt: row.updated_at, lastOpenedAt: row.last_opened_at })

export class DevBoxStore {
  private db: Database.Database
  constructor(path: string) { mkdirSync(dirname(path), { recursive: true }); this.db = new Database(path); this.migrate() }
  private migrate(): void {
    this.db.exec(`PRAGMA foreign_keys = ON;
      CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL COLLATE NOCASE UNIQUE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, last_opened_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS preferences (workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, key TEXT NOT NULL, value_json TEXT NOT NULL, PRIMARY KEY(workspace_id,key));
      CREATE TABLE IF NOT EXISTS integrations (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, provider TEXT NOT NULL, state TEXT NOT NULL, display_name TEXT, config_json TEXT NOT NULL DEFAULT '{}', last_synced_at TEXT, last_error TEXT);
      CREATE TABLE IF NOT EXISTS source_entities (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, integration_id TEXT REFERENCES integrations(id) ON DELETE CASCADE, provider TEXT NOT NULL, provider_id TEXT NOT NULL, type TEXT NOT NULL, title TEXT NOT NULL, url TEXT NOT NULL, status TEXT, updated_at TEXT NOT NULL, payload_json TEXT NOT NULL DEFAULT '{}', UNIQUE(integration_id, provider_id, type));
      CREATE TABLE IF NOT EXISTS secret_references (integration_id TEXT PRIMARY KEY REFERENCES integrations(id) ON DELETE CASCADE, encrypted_blob BLOB NOT NULL);
      CREATE TABLE IF NOT EXISTS work_items (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, integration_id TEXT NOT NULL REFERENCES integrations(id) ON DELETE CASCADE, source_entity_id TEXT NOT NULL REFERENCES source_entities(id) ON DELETE CASCADE, title TEXT NOT NULL, reason TEXT NOT NULL, priority TEXT NOT NULL, url TEXT NOT NULL, kind TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(integration_id, source_entity_id));
      CREATE TABLE IF NOT EXISTS app_state (key TEXT PRIMARY KEY, value TEXT NOT NULL);`)
  }
  createWorkspace(rawName: string): Workspace { const name = validateName(rawName); const now = new Date().toISOString(); const workspace = { id: randomUUID(), name, createdAt: now, updatedAt: now, lastOpenedAt: now }; this.db.prepare('INSERT INTO workspaces VALUES (@id,@name,@createdAt,@updatedAt,@lastOpenedAt)').run(workspace); this.selectWorkspace(workspace.id); return workspace }
  listWorkspaces(): WorkspaceSummary[] { return this.db.prepare(`SELECT w.*, count(i.id) integration_count FROM workspaces w LEFT JOIN integrations i ON i.workspace_id=w.id GROUP BY w.id ORDER BY w.last_opened_at DESC`).all().map((r) => ({ ...map(r as Row), integrationCount: Number((r as { integration_count: number }).integration_count) })) }
  getWorkspace(id: string): Workspace | null { const row = this.db.prepare('SELECT * FROM workspaces WHERE id=?').get(id) as Row | undefined; return row ? map(row) : null }
  currentWorkspace(): Workspace | null { const current = this.db.prepare("SELECT value FROM app_state WHERE key='current_workspace_id'").get() as { value: string } | undefined; return current ? this.getWorkspace(current.value) : null }
  selectWorkspace(id: string): Workspace { const workspace = this.require(id); const now = new Date().toISOString(); this.db.prepare('UPDATE workspaces SET last_opened_at=?, updated_at=? WHERE id=?').run(now, now, id); this.db.prepare("INSERT INTO app_state(key,value) VALUES ('current_workspace_id',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(id); return { ...workspace, updatedAt: now, lastOpenedAt: now } }
  renameWorkspace(id: string, rawName: string): Workspace { this.require(id); const name = validateName(rawName); const now = new Date().toISOString(); this.db.prepare('UPDATE workspaces SET name=?, updated_at=? WHERE id=?').run(name, now, id); return { ...this.require(id), name, updatedAt: now } }
  deleteWorkspace(id: string, confirmationName: string): void { const workspace = this.require(id); if (workspace.name !== confirmationName.trim()) throw new Error('Workspace name does not match confirmation.'); this.db.prepare('DELETE FROM workspaces WHERE id=?').run(id); if (this.currentWorkspace()?.id === id) this.db.prepare("DELETE FROM app_state WHERE key='current_workspace_id'").run() }
  getTheme(workspaceId: string): 'dark' | 'light' | 'system' { this.require(workspaceId); const r = this.db.prepare("SELECT value_json FROM preferences WHERE workspace_id=? AND key='theme'").get(workspaceId) as { value_json: string } | undefined; return r ? JSON.parse(r.value_json) : 'dark' }
  setTheme(workspaceId: string, value: 'dark' | 'light' | 'system'): void { this.require(workspaceId); this.db.prepare("INSERT INTO preferences VALUES (?, 'theme', ?) ON CONFLICT(workspace_id,key) DO UPDATE SET value_json=excluded.value_json").run(workspaceId, JSON.stringify(value)) }
  createGitHubIntegration(workspaceId: string, displayName: string, token: Buffer, repositories: string[]): string { this.require(workspaceId); this.removeGitHub(workspaceId); const id = randomUUID(); this.db.prepare('INSERT INTO integrations(id,workspace_id,provider,state,display_name,config_json) VALUES (?,?,\'github\',\'connected\',?,?)').run(id, workspaceId, displayName, JSON.stringify({ repositories })); this.db.prepare('INSERT INTO secret_references VALUES (?,?)').run(id, token); return id }
  getToken(id: string): Buffer { const row = this.db.prepare('SELECT encrypted_blob FROM secret_references WHERE integration_id=?').get(id) as { encrypted_blob: Buffer } | undefined; if (!row) throw new Error('GitHub credentials are unavailable.'); return row.encrypted_blob }
  githubIntegrations(workspaceId: string): IntegrationSummary[] { this.require(workspaceId); return this.db.prepare("SELECT * FROM integrations WHERE workspace_id=? AND provider='github'").all(workspaceId).map((r) => { const x = r as { id:string; state:IntegrationSummary['state']; display_name:string; last_synced_at:string|null; last_error:string|null; config_json:string }; const config = JSON.parse(x.config_json) as { repositories:string[] }; return { id:x.id, provider:'github', state:x.state, displayName:x.display_name, lastSyncedAt:x.last_synced_at, lastError:x.last_error, repositories:config.repositories.map((fullName) => ({ fullName, selected:true })) } }) }
  setRepositories(id: string, repositories: string[]): void { this.db.prepare('UPDATE integrations SET config_json=? WHERE id=? AND provider=\'github\'').run(JSON.stringify({ repositories }), id) }
  integration(id: string): { id:string; workspaceId:string; repositories:string[] } { const x = this.db.prepare("SELECT id,workspace_id,config_json FROM integrations WHERE id=? AND provider='github'").get(id) as { id:string; workspace_id:string; config_json:string } | undefined; if (!x) throw new Error('GitHub integration not found.'); return { id:x.id, workspaceId:x.workspace_id, repositories:(JSON.parse(x.config_json) as {repositories:string[]}).repositories } }
  removeGitHub(workspaceId: string): void { this.db.prepare("DELETE FROM integrations WHERE workspace_id=? AND provider='github'").run(workspaceId) }
  replaceGitHubWork(id: string, items: Array<Omit<WorkItem, 'id'>>): void { const integration = this.integration(id); const transaction = this.db.transaction(() => { this.db.prepare('DELETE FROM work_items WHERE integration_id=?').run(id); this.db.prepare('DELETE FROM source_entities WHERE integration_id=?').run(id); for (const item of items) { const sourceId = randomUUID(); this.db.prepare('INSERT INTO source_entities(id,workspace_id,integration_id,provider,provider_id,type,title,url,status,updated_at,payload_json) VALUES (?,?,?,?,?,?,?,?,?,?,\'{}\')').run(sourceId,integration.workspaceId,id,'github',item.url,item.kind,item.title,item.url,item.priority,item.updatedAt); this.db.prepare('INSERT INTO work_items VALUES (?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),integration.workspaceId,id,sourceId,item.title,item.reason,item.priority,item.url,item.kind,item.updatedAt) } this.db.prepare('UPDATE integrations SET last_synced_at=?,last_error=NULL WHERE id=?').run(new Date().toISOString(),id) }); transaction() }
  markIntegrationError(id: string, state: 'needs_reauth' | 'error', error: string): void { this.db.prepare('UPDATE integrations SET state=?,last_error=? WHERE id=?').run(state,error,id) }
  workItems(workspaceId: string): WorkItem[] { return this.db.prepare('SELECT id,title,reason,priority,url,updated_at,kind FROM work_items WHERE workspace_id=? ORDER BY CASE priority WHEN \'urgent\' THEN 0 WHEN \'high\' THEN 1 ELSE 2 END, updated_at DESC').all(workspaceId).map((r) => { const x=r as {id:string;title:string;reason:string;priority:WorkItem['priority'];url:string;updated_at:string;kind:WorkItem['kind']}; return {id:x.id,title:x.title,reason:x.reason,priority:x.priority,url:x.url,updatedAt:x.updated_at,kind:x.kind} }) }
  close(): void { this.db.close() }
  private require(id: string): Workspace { const workspace = this.getWorkspace(id); if (!workspace) throw new Error('Workspace not found.'); return workspace }
}
export function validateName(value: string): string { const name = value.trim(); if (!name || name.length > 80) throw new Error('Workspace name must be between 1 and 80 characters.'); return name }
